### PR TITLE
Updated swift-syntax to match Swift 5.3

### LINKED ISSUE #199: Error: Could not parse syntax tree of Swift file.
Hi,

I´m trying to use Bartycrouch in my project but when my Swift files are being parsed a got the following warnings for each of them: `Could not parse syntax tree of Swift file.`.
(./Project/AppDelegate.swift:  Could not parse syntax tree of Swift file.)

I also got the following warning: `Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.`, even when I have the file in my project.

My storyboards are correctly updated.

Swift version: 5.2
BartyCrouch version: 4.2.0
XCode version: 11.3.1

I have tried to execute BartyCrouch with the verbose option but it doesn´t provide more information.

Any idea what can be causing the problem?

### LINKED ISSUE #201: BartyCrouch:  Could not parse syntax tree of Swift file.
## Expected Behavior
No warning's should show

## Actual Behavior
Two warnings shows as follows

-  BartyCrouch:  Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.
- BartyCrouch:  Could not parse syntax tree of Swift file. #199 

## Steps to Reproduce the Problem

  1.  Open any project on Xcode 12.0 (12A7209)
  2. Proceed to build project with implmentation
  3. Then in the build warnings you will get the following errors [September 23rd, 2020]

## Specifications

  - Version: iOS 14
  - Platform: Mac OS
  - IDE Version:  Xcode 12.0 (12A7209)

## Example
Screen Shot 2020-09-23 at 1 17 46 AM

### PR DESCRIPTION
**Pull request by w8wjb**
Fixes #199
Fixes #201

### CODE REVIEW

**Comment by trujamal** [comment]
@Jeehut

**Comment by Jeehut** [comment]
Looks good to me. :+1:

**Comment by Jeehut** [comment]
@w8wjb Thank you for the fix.

I just released version 4.3.0 with this, but I didn't have time to test it properly, I just ran the tests which were passing fine with Xcode 12.0. Tell me if anything's not working as expected. Note that [this PR](https://github.com/Homebrew/homebrew-core/pull/61734) needs to be merged before the new version will be available via Homebrew Core.

**Comment by khorbushko** [comment]
hi, this issue reproduced now with Xcode 13

**Pull request merged**
