### PR TITLE
Add support for multiple strings files

### LINKED ISSUE #20: How to work with multiple strings files
I have multiple string files in my project and I use them using 

``` swift
NSLocalizedString("Please add description.", tableName: "SellForm", bundle: NSBundle.mainBundle(), value: "", comment: "")
```

but BC doesn't seem to recognize my SellForm.strings file

### PR DESCRIPTION
**Pull request by mathebox**
With this PR, it becomes possible to use multiple strings files in a project when using the `--extract-loc-strings` option. If a `NSLocalizedString` call specifies a specific table name, the key will be put in the according file.

For example, the usage of `NSLocalizedString("key", tableName: "CustomName", comment: "...")` will require a `CustomName.strings` file. 

Because of this, a `Localizable.strings` file is no longer strictly required. Any other `.string` file will also work.

Fixes #20

**Question:**
`StringsFilesSearch.findAllStringsFiles(within baseDirectoryPath: String, withFileName fileName: String)` is currently not used. This method might helpful for future functionality. Should I remove this method anyway?

### CODE REVIEW

**Comment by mathebox** [comment]
Apparently, there is a problem. BartyCrouch tries to localize .strings files of storyboard files. I'll look into this.

**Comment by Dschee** [comment]
Hi @mathebox, thank you for this PR. Did you succeed in fixing the issue?

Also, could you please update your commit messages to conform to the [contribution guidelines](https://github.com/Flinesoft/BartyCrouch#contributing)? Mainly you need to remove the dot at the end of your commit messages.

**Comment by mathebox** [comment]
Hi @Dschee. Yes, I fixed the problem. `.strings` files are going to be exclude if there is an `storyboard` or `xib` files with the same name.

Feel free to use 'merge & squash' for this pull request.

**Comment by Dschee** [comment]
@mathebox Thank you for this PR, looks good to me and the tests seem to pass as well. Merging this.

**Comment by Dschee** [comment]
Gonna wait a bit and see if #73 is finished soon and release in a few days at the latest.

**Comment by Dschee** [comment]
Unfortunately your solution had unexpected side effects. See #11 for more details.

**Pull request merged**
