### PR TITLE
[WIP] Break generator tests for more keys in example

### PR DESCRIPTION
**Pull request by kafejo**
As you can see, I added more keys and at the end they are sorted alphabetically. The strange behaviour that sometimes it just add key somewhere in the middle I cannot reproduce right know, but I will keep trying.

### CODE REVIEW

**Comment by kafejo** [comment]
see #26

**Comment by Dschee** [comment]
Thank you for the PR, @kafejo. I just had a look into your changes and made the following observations: Your test only proves that the `genstrings` command sorts by keys. But if I understood your scenario from #26 correctly, then this is your situation:

- You already have a Localizable.strings file with (say) 3 keys: "A", "C", "E"
- You add 2 new `NSLocalizedString` keys ("D" and "B") into your project and build
You observed:
- The resulting Localizable.strings contains: "A", "B", "C", "D", "E"
You expected:
- The resulting Localizable.strings contains: "A", "C", "E", "D", "B"

Your current test changes don't prove that your observations are actually the case though. They only prove that the newly added keys ("D" and "B") are sorted resulting in this (using the above example): "A", "C", "E", "B", "D". I hope you understand what I mean.

I think the right place to add such a test would be the currently empty `CommandLineActorTests.swift` file by testing the method `actOnCode(path:, override:, verbose:, localizable:, defaultToKeys:, additive:)` with a similar scenario like I explained above (so an existing `.strings` file which is being updated like in the StringsFileUpdaterTests).

**Comment by kafejo** [comment]
Alright, I will look into that as soon as I have a little bit of spare time.

**Comment by Dschee** [comment]
See my comment [here](https://github.com/Flinesoft/BartyCrouch/issues/26#issuecomment-242913786) – I've implemented the said test and couldn't reproduce the issue. You can go on from there – I hope we can find the issue and fix it soon! :)

**Comment by Dschee** [comment]
I'm closing this since we have found out this was not actually the issue anyway. See #21 for more info.

**Comment by Dschee** [comment]
Closing due to inactivity.

**Pull request closed without merging**
