### PR TITLE
Allow BartyCrouch to run in sub-folder

### PR DESCRIPTION
**Pull request by zufuliu**
Allow BartyCrouch to run in sub-folder, sometimes this maybe useful.

### CODE REVIEW

**Comment by Dschee** [comment]
Thanks for the PR! Could you add a test that fails without your change so we can make sure this feature keeps working over time?

**Comment by zufuliu** [comment]
Assume a project with this structure:
```
SampleApp1
----SampleApp
     ----Base.lproj
     ----xx.lproj
----SampleApp.xcodeproj
```
Without this PR, when running BartyCrouch using SampleApp as path like:
```
bartycrouch interfaces -p SampleApp1/SampleApp
```

it can't find xib/storyboard inside Base.lproj, because original RegExp requres a slash before Base.lproj, This PR make the slash optional.

**Comment by zufuliu** [comment]
I'm sorry, there is a bug in my RexExp, the entire string before Base.lproj should marked as optional, not only the slash. so it matches Base.lproj and xxx/Base.lproj, but not backup-Base.lproj. The correct RegExp (before escape) is `^(.*/)?Base\.lproj`

**Comment by zufuliu** [comment]
I had updated my RegExp.

**Comment by Dschee** [comment]
Thanks for the fixed regex. What about the test?

**Comment by zufuliu** [comment]
Is something like this could enough for test?

```swift
	func testFindAllIBFilesSub() {
		let basePath = "\(BASE_DIR)/Tests/Assets/Storyboards/"

		let expectedIBFilePaths = ["iOS", "OSX", "tvOS"].map { examplePath(platform: $0, locale: "Base", type: "storyboard") }

		var results = [String]()
		["iOS", "OSX", "tvOS"].forEach { (platform) in
			results += StringsFilesSearch.shared.findAllIBFiles(within: basePath + platform, withLocale: "Base")
		}

		XCTAssertEqual(results.count, expectedIBFilePaths.count)
		XCTAssertEqual(results.sorted(), expectedIBFilePaths.sorted())
	}
```

**Comment by zufuliu** [comment]
run this test with original code, result as:
```
Test Case '-[BartyCrouchTests.StringsFilesSearchTests testFindAllIBFilesSub]' started.
/Users/apple/work/ios/BartyCrouch1/Tests/Code/StringsFilesSearchTests.swift:35: error: -[BartyCrouchTests.StringsFilesSearchTests testFindAllIBFilesSub] : XCTAssertEqual failed: ("0") is not equal to ("3") - 
/Users/apple/work/ios/BartyCrouch1/Tests/Code/StringsFilesSearchTests.swift:36: error: -[BartyCrouchTests.StringsFilesSearchTests testFindAllIBFilesSub] : XCTAssertEqual failed: ("[]") is not equal to ("["/Users/apple/work/ios/BartyCrouch1/Tests/Assets/Storyboards/OSX/Base.lproj/Example.storyboard", "/Users/apple/work/ios/BartyCrouch1/Tests/Assets/Storyboards/iOS/Base.lproj/Example.storyboard", "/Users/apple/work/ios/BartyCrouch1/Tests/Assets/Storyboards/tvOS/Base.lproj/Example.storyboard"]") - 
Test Case '-[BartyCrouchTests.StringsFilesSearchTests testFindAllIBFilesSub]' failed (1.130 seconds).
Test Suite 'StringsFilesSearchTests' failed at 2018-02-08 15:48:41.110.
	 Executed 1 test, with 2 failures (0 unexpected) in 1.130 (1.132) seconds
Test Suite 'BartyCrouchTests.xctest' failed at 2018-02-08 15:48:41.111.
	 Executed 1 test, with 2 failures (0 unexpected) in 1.130 (1.134) seconds
Test Suite 'Selected tests' failed at 2018-02-08 15:48:41.112.
	 Executed 1 test, with 2 failures (0 unexpected) in 1.130 (1.136) seconds
Program ended with exit code: 1
```
with this PR:
```
Test Case '-[BartyCrouchTests.StringsFilesSearchTests testFindAllIBFilesSub]' started.
Test Case '-[BartyCrouchTests.StringsFilesSearchTests testFindAllIBFilesSub]' passed (0.757 seconds).
Test Suite 'StringsFilesSearchTests' passed at 2018-02-08 15:50:20.619.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.757 (0.759) seconds
Test Suite 'BartyCrouchTests.xctest' passed at 2018-02-08 15:50:20.620.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.757 (0.761) seconds
Test Suite 'Selected tests' passed at 2018-02-08 15:50:20.621.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.757 (0.764) seconds
Program ended with exit code: 0
```

**Comment by zufuliu** [comment]
Test code added.

**Comment by Dschee** [comment]
Thank you, looks good.

**Comment by robmaceachern** [comment]
I just ran in to the same problem. Thanks for fixing this @zufuliu 👍 . @Dschee would you be able to push a release to cocoapods to pick up this change?

**Pull request merged**
