### PR TITLE
Add option to parse custom functions

### PR DESCRIPTION
**Pull request by crystalstorm**
In cases like <a href="http://stackoverflow.com/questions/9939885/manual-language-selection-in-an-ios-app-iphone-and-ipad">this one </a> where you may use custom function/macro instead of NSLocalizedString you need a way to tell the tool to parse your function name. It uses "genstrings" to extract the strings and it has this "-s functionName" argument so I just added it as an option.
I've named it "customFunction" with "c" as shorthand. 

This is the way you use it:
`$ bartycrouch code -p "/path/to/code/files" -l "/path/to/Localizables" -c "YourCustomFunction"`

I've updated the Readme about the new feature.
I used the tool in such case so I needed this feature added :)

### CODE REVIEW

**Comment by Dschee** [comment]
Thank you for helping to improve BartyCrouch! 👍 

I agree that this is helpful in some situations, I'll have a look at it this weekend at latest and will also try to make sure the CI integration works correctly (it's not your fault it's failing right now).

But two things I already noticed:

1. The commit messages of this project follow a specific structure convention (although unnoticed in the README – another thing to update). I'd appreciate it if you could follow that structure, too. Specifically some of your messages are a bit too long and don't begin with an uppercase letter. See [this](http://chris.beams.io/posts/git-commit/) post for more information on the rationale.

2. There are no tests for the new command line option you added. My goal is to have every documented feature covered with tests so people who read the README and use a feature can rely on it to work going forward. If you could add one test at least that would be great!

**Comment by crystalstorm** [comment]
1. Alright I'll write better commit messages.
2. About the tests also OK. I've looked into CommandLineParserTests and CommandLineActorTests but they are empty now. May you provide some example how I can test there the new things?

**Comment by Dschee** [comment]
Right, the parser and actor were recently refactored into the framework target so they can be tested, but I didn't have time to write tests for them yet, so no issues there. There is a test for GenStringsCommander though which is where you could add a second method for your test case. You'll probably want to add a Swift file within Tests/Assets/CodeFiles with a custom function as input data. I hope this gets you started with the test. Should be pretty similar to the existing test in that file.

**Comment by Dschee** [comment]
I just created **a new branch named `work/custom_function`** for this feature and cherry picked your commits so far. I also corrected your commit messages and improved some parts of your implementation and documentation updates.

Now **the only step left** to get this feature finished is **writing a test** – please setup a Swift file within Tests/Assets/CodeFiles with some code that uses a custom function and add a new test method named similar to `testExampleCodeFilesWithCustomFunction()` within `GenStringsCommanderTests` and write code that tests this feature.

Note: Before you implement the test please **delete your fork** and **refork BartyCrouch** to ensure you can use the new branch including the rebased commits. Once you are finished send a new pull request and I'll merge it (given all tests pass – I fixed the CI integration). I'm closing this in the meantime.

Thank you for helping to improve BartyCrouch! 👍

**Comment by Dschee** [comment]
@crystalstorm: Did you make any progress here?
I think the only missing thing was a test, then I could merge.

**Comment by crystalstorm** [comment]
Sorry mate. No progress at all. I'm in some hectic times at work and didn't had much free moments to look at it. Sorry if I'm stoping you :(

**Comment by Dschee** [comment]
No worries, I just think it would be a nice addition which might already work, so there's not much work to do any more. Never mind, take your time. Or maybe someone else will need this feature and can finish it later. Thanks for answering! 👍

**Pull request closed without merging**
